# AICP Internship Task Week 1

### Question#1: Write a NumPy program to create an array of all even integers from 30 to 70.

In [16]:
import numpy as np
even_integers = np.arange(30, 71, 2)
print(even_integers)


[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


### Question#2: Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [17]:
import numpy as np
random_numbers = np.random.randn(15)
print(random_numbers)


[-0.98634117 -0.40046954 -1.31519043  1.18090042 -0.8878818  -1.25529918
 -1.67853462 -1.09432078  0.58791997  0.54261672 -0.29288287 -1.08882153
 -1.36938192 -1.10921321  0.4232685 ]


### Question#3: How to compute the cross-product of two matrices in NumPy?

In NumPy, you can compute the cross-product of two matrices using the numpy.cross() function. The cross() function calculates the cross product of two arrays along a specified axis.

In [21]:
import numpy as np
matrixX = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
matrixY = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])
cross_product = np.cross(matrixX, matrixY)
print("Cross-Product Matrix:")
print(cross_product)


Cross-Product Matrix:
[[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]


### Question#4: How to compute the determinant of an array using NumPy?

The determinant of a 2x2 matrix. 

In [7]:
import numpy as np
matrix = np.array([[4, 7],
                   [2, 6]])
determinant = np.linalg.det(matrix)
print("Matrix:")
print(matrix)
print("\nDeterminant of the matrix:", determinant)

Matrix:
[[4 7]
 [2 6]]

Determinant of the matrix: 10.000000000000002


### Question#5: How to create a 3x3x3 array with random values using NumPy?

In [8]:
import numpy as np
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.88414675 0.21865623 0.80511546]
  [0.39164952 0.70255935 0.87498741]
  [0.80887758 0.35349349 0.16599024]]

 [[0.60116512 0.85766841 0.5555882 ]
  [0.29361985 0.07945857 0.2741869 ]
  [0.01876198 0.0860361  0.6628619 ]]

 [[0.87293823 0.12186092 0.07418273]
  [0.4047791  0.16705887 0.78490287]
  [0.4628668  0.71736516 0.1997008 ]]]


### Question#6: How to create a 5x5 array with random values and find the minimum and maximum values using NumPy?

In [12]:
import numpy as np

random_array = np.random.rand(5, 5)

print("Array:")
print(random_array)

min_value = np.min(random_array)
max_value = np.max(random_array)

print("\nMinimum value:", min_value)
print("Maximum value:", max_value)


Array:
[[0.4661109  0.16343176 0.57386239 0.0263351  0.5518219 ]
 [0.0811658  0.54878144 0.52289107 0.30942273 0.39296672]
 [0.29535553 0.15728994 0.30260925 0.84176652 0.16892048]
 [0.45179198 0.93554024 0.8374889  0.65148057 0.69649098]
 [0.79492359 0.50518175 0.48974763 0.59962009 0.47635239]]

Minimum value: 0.026335095309271028
Maximum value: 0.9355402415638367


### Question#7: How to compute the mean, standard deviation, and variance of a given array along the second axis in NumPy?

In [19]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
mean_values = np.mean(array, axis=1)
std_dev_values = np.std(array, axis=1)
variance_values = np.var(array, axis=1)
print("Original Array:")
print(array)
print("\nMean along the second axis:")
print(mean_values)
print("\nStandard Deviation along the second axis:")
print(std_dev_values)
print("\nVariance along the second axis:")
print(variance_values)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Mean along the second axis:
[ 2.5  6.5 10.5]

Standard Deviation along the second axis:
[1.11803399 1.11803399 1.11803399]

Variance along the second axis:
[1.25 1.25 1.25]


### Created by: Malik M SHahmeer Rashid